<?php
require('assets/fpdf/fpdf.php');

class PDF extends FPDF
{
    // Page header
    function Header()
    {
        $this->SetFont('Arial','B',8);
        $this->Cell(18,10,"CS CODE");
        $this->Cell(50,10,"DESCRIPTION");
        $this->Cell(35,10,"CALIBRATION DATE");
        $this->Cell(35,10,"NEXT CALIBRATION");
        $this->Cell(24,10,"LOCATION");
        $this->Cell(10,10,"REMARKS");
        $this->Ln(7);// Line break
        $this->Line(11, 18, 215-27, 18);//line
    }

    // Page footer
    function Footer()
    {
        $this->SetY(-15);// Position at 1.5 cm from bottom
        $this->SetFont('Arial','I',8);// Arial italic 8
        $this->Cell(0,10,'Page '.$this->PageNo().'/{nb}',0,0,'C');// Page number
    }
}

// Instanciation of inherited class
$pdf = new PDF();
$pdf->SetTitle($this->pdfTitle);
$pdf->AliasNbPages();
$pdf->AddPage();

if($this->contentResults){
    foreach($this->contentResults as $list){
        
        $pdf->SetFont('Arial','',7);
        $pdf->Cell(18,10,$list['cs_code']);
        $pdf->Cell(50,10,$list['description']);
        $pdf->Cell(35,10,date("M d, Y",  strtotime($list['date_calibration'])));
        $pdf->Cell(35,10,date("M d, Y",  strtotime($list['next_calibration'])));
        $pdf->Cell(24,10,$list['location']);
        $pdf->Cell(10,10,$list['remarks']);
        $pdf->Ln(5);// Line break
    } 
}
$pdf->Output();