<script src="<?php echo $this->baseUrl(); ?>/assets/calibration/plugins/jQuery/jQuery-2.2.0.min.js"></script>
<script src="<?php echo $this->baseUrl(); ?>/assets/js/calibration/calibration.js"></script>

<div class="row">
    <div class="col-md-12">
      <!-- general form elements -->
      <div class="box box-primary">
        <div class="box-header with-border">
          <h3 class="box-title">Record Calibration</h3>
        </div>
        <!-- /.box-header -->
        <div class="box-body">
<!--          <a href="javascript:;" id="addRecord" class="pull-right btn btn-primary" style="margin-right: 2px;"><i class="fa fa-fw fa-plus"></i> Add Record</a>-->
          <a target="_blank" href="fpdf-print?page=calibration&start_date=<?php echo $this->start_date;?>&end_date=<?php echo $this->end_date; ?>" class="pull-right btn btn-primary" style="margin-right: 2px;"><i class="fa fa-fw fa-print"></i> Print</a>
          
          <br /><br /><br />
          <table id="recordTable" class="table table-bordered table-hover">
            <thead>
            <tr>
              <th>CS Code</th>
              <th>Description</th>
              <th>Manufacturer</th>
              <th>Date Calibration</th>
              <th>Present Status</th>
              <th>Action</th>
            </tr>
            </thead>
            <tbody>

            <?php foreach ($this->recordCalibration as $list) { ?>
                <tr>
                    <td><?php echo $list['cs_code']; ?></td>
                    <td><?php echo $list['description']; ?></td>
                    <td><?php echo $list['manufacturer']; ?></td>
                    <td><?php echo date("M d, Y",strtotime($list['date_calibration'])); ?></td>
                    <td><?php echo $list['status']; ?></td>
                    <td class='center'>
                            <a onclick="viewCalibrationContent(<?php echo $list['id'] ?>)" href="javascript:;"> View </a> |
                            <a onclick="editCalibrationContent(<?php echo $list['id'] ?>)" href="javascript:;"> Edit </a>
<!--                            <a onclick="deleteCalibrationEntry(<?php echo $list['id'] ?>)" href="javascript:;"> Delete </a>-->
                    </td>

                </tr>

            <?php } ?>

            </tbody>
            <tfoot>
            <tr>
              <th>CS Code</th>
              <th>Description</th>
              <th>Manufacturer</th>
              <th>Date Calibration</th>
              <th>Present Status</th>
              <th>Action</th>
            </tr>
            </tfoot>
          </table>
        </div>
      </div>
      <!-- /.box -->

    </div>
</div>

<!-- Modal -->
<div class="modal  bs-example-modal" id="scheduleModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Calibration Details</h4>
      </div>
      <div class="modal-body">
          <div id="schedule-content"></div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary" id="update-btn" style="display:none;">Update</button>
      </div>
    </div>
  </div>
</div>

<!-- Modal -->
<div class="modal  bs-example-modal" id="calibrationModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Calibration Record</h4>
      </div>
      <form method="POST">
      <div class="modal-body">
          <div id="AddRecord-form">
              <div class="input-group col-md-10">
                <label class="control-label" for="description">Description :</label>
                <input type="text" class="form-control" name="description" placeholder="Description" />
              </div>
              <div class="input-group col-md-10">
                <label class="control-label" for="description">Manufacturer :</label>
                <input type="text" class="form-control" name="manufacturer" placeholder="Manufacturer" />
              </div>
              <div class="input-group col-md-10">
                <label class="control-label" for="description">Serial No. :</label>
                <input type="text" class="form-control" name="serialNo" placeholder="Serial No." />
              </div>
              <div class="input-group col-md-10">
                <label class="control-label" for="description">Frequency :</label>
                <input type="text" class="form-control" name="frequency" placeholder="Frequency" />
              </div>
              <div class="input-group col-md-10">
                <label class="control-label" for="description">Date of Calibration :</label>
                <input type="text" class="form-control" name="dateCalibration" placeholder="Date of Calibration" />
              </div>
              <div class="input-group col-md-10">
                <label class="control-label" for="description">Next Calibration :</label>
                <input type="text" class="form-control" name="nextCalibration" placeholder="Next Calibration" />
              </div>
              <div class="input-group col-md-10">
                <label class="control-label" for="description">Location :</label>
                <input type="text" class="form-control" name="location" placeholder="Location" />
              </div>
              <div class="input-group col-md-10">
                <label class="control-label" for="description">Machine Tolerance :</label>
                <input type="text" class="form-control" name="machineTolerance" placeholder="Machine Tolerance" />
              </div>
              <div class="input-group col-md-10">
                <label class="control-label" for="description">Current Status :</label>
                <input type="text" class="form-control" name="currentStatus" placeholder="Current Status" />
              </div>
              <div class="input-group col-md-10">
                <label class="control-label" for="description">CAL Duration :</label>
                <input type="text" class="form-control" name="calDuration" placeholder="CAL Duration" />
              </div>
              <div class="input-group col-md-10">
                <label class="control-label" for="description">Calibrated By :</label>
                <input type="text" class="form-control" name="calibratedBy" placeholder="Calibrated By" />
              </div>
              <div class="input-group col-md-10">
                <label class="control-label" for="description">Remarks :</label>
                <input type="text" class="form-control" name="remarks" placeholder="Remarks" />
              </div>
              <div class="input-group col-md-10">
                <label class="control-label" for="description">Calibration Procedure :</label>
                <input type="text" class="form-control" name="calProcedure" placeholder="Calibration Procedure" />
              </div>
              <div class="input-group col-md-10">
                <label class="control-label" for="description">Calibration Report No. :</label>
                <input type="text" class="form-control" name="calReportNo" placeholder="Calibration Report No." />
              </div>
              <div class="input-group col-md-10">
                <label class="control-label" for="description">GR&R :</label>
                <input type="text" class="form-control" name="grr" placeholder="GR&R" />
              </div>
          </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary" id="update-btn" style="display:none;">Update</button>
        <button type="button" class="btn btn-primary" id="add-btn" style="display:none;">Add</button>
      </div>
      </form>
    </div>
  </div>
</div>