<script src="<?php echo $this->baseUrl(); ?>/assets/calibration/plugins/jQuery/jQuery-2.2.0.min.js"></script>
<script src="<?php echo $this->baseUrl(); ?>/assets/js/calibration/calibration.js"></script>

<!-- left column -->
<div class="row">
    <div class="col-md-12">
      <!-- general form elements -->
      <div class="box box-primary">
        <div class="box-header with-border">
          <h3 class="box-title">Record GR&R Study</h3>
        </div>
        <!-- /.box-header -->
        <div class="box-body">
          <a target="_blank" href="fpdf-print?page=grStudy&content=<?php echo $this->content; ?>" class="pull-right btn btn-primary" style="margin-right: 2px;"><i class="fa fa-fw fa-print"></i> Print</a>
          <br /><br /><br />
          <table id="recordTable" class="table table-bordered table-hover">
            <thead>
            <tr>
              <th>CS Code</th>
              <th>Description</th>
              <th>Manufacturer</th>
              <th>Date Calibration</th>
              <th>Present Status</th>
              <th>Action</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($this->grStudyContent as $list) { ?>
                <tr>
                    <td><?php echo $list['cs_code']; ?></td>
                    <td><?php echo $list['description']; ?></td>
                    <td><?php echo $list['manufacturer']; ?></td>
                    <td><?php echo date("M d, Y",strtotime($list['date_calibration'])); ?></td>
                    <td><?php echo $list['status']; ?></td>
                    <td class='center'>
                            <a onclick="viewCalibrationContent(<?php echo $list['id'] ?>)" href="javascript:;"> View </a> |
                            <a onclick="editCalibrationContent(<?php echo $list['id'] ?>)" href="javascript:;"> Edit </a>
<!--                            <a onclick="deleteCalibrationEntry(<?php echo $list['id'] ?>)" href="javascript:;"> Delete </a>-->
                    </td>

                </tr>

            <?php } ?>
            </tbody>
            <tfoot>
            <tr>
              <th>CS Code</th>
              <th>Description</th>
              <th>Manufacturer</th>
              <th>Date Calibration</th>
              <th>Present Status</th>
              <th>Action</th>
            </tr>
            </tfoot>
          </table>
        </div>
      </div>
      <!-- /.box -->

    </div>
</div>


<!-- Modal -->
<div class="modal  bs-example-modal" id="scheduleModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Calibration Details</h4>
      </div>
      <div class="modal-body">
          <div id="schedule-content"></div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary" id="update-btn" style="display:none;">Update</button>
      </div>
    </div>
  </div>
</div>