<?php 
    //set default date and time
    date_default_timezone_set("Asia/Manila");
    
    //get today's date
    $today = new DateTime('now');
    
    //get tomorrow's date
    $tomorrow = new DateTime('tomorrow'); 
    
    //next other day
    $nextDay2 = new DateTime($today->format('Y-m-d H:i:s'));
    $nextDay2->modify('+2 day');
?>
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Calibration Recall System</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <!-- start: Favicon -->
  <link rel="shortcut icon" href="<?php echo $this->baseUrl(); ?>/assets/bootstrap/img/calibration.jpg">
  <!-- end: Favicon -->
  <!-- Bootstrap 3.3.5 -->
  <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/assets/calibration/bootstrap/css/bootstrap.min.css">
  <!-- iCheck for checkboxes and radio inputs -->
  <link rel="stylesheet" href="?php echo $this->baseUrl(); ?>/assets/plugins/iCheck/all.css" />
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/assets/calibration/dist/css/AdminLTE.min.css">
  <!-- AdminLTE Skins. Choose a skin from the css/skins
       folder instead of downloading all of them to reduce the load. -->
  <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/assets/calibration/dist/css/skins/_all-skins.min.css">
  <!-- daterange picker -->
  <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/assets/calibration/plugins/daterangepicker/daterangepicker-bs3.css">

  <style>
      .callout1{
            border-radius: 3px;
            margin: 0 0 20px 0;
            padding: 15px 30px 15px 15px;
            border-left: 5px solid #F39C12;
      }
      .callout.callout-warning1{
              background-color: #F5DEB3;
      }
  </style>
  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
</head>
<body class="hold-transition skin-blue sidebar-mini">
<!-- Site wrapper -->
<div class="wrapper">

  <header class="main-header">
    <!-- Logo -->
    <a href="<?php echo $this->baseUrl(); ?>/calibration" class="logo">
      <!-- mini logo for sidebar mini 50x50 pixels -->
      <span class="logo-mini"><b>CRS</b></span>
      <!-- logo for regular state and mobile devices -->
      <span class="logo-lg">CALIBRATION</span>
    </a>
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top" role="navigation">
      <!-- Sidebar toggle button-->
      <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>

      <div class="navbar-custom-menu">
        <ul class="nav navbar-nav">
          
          <!-- User Account: style can be found in dropdown.less -->
          <li class="dropdown user user-menu">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <img src="<?php echo $this->baseUrl(); ?>/assets/calibration/dist/img/profile.png" class="user-image" alt="User Image">
              <span class="hidden-xs">Administrator</span>
            </a>
            <ul class="dropdown-menu">
              <!-- User image -->
              <li class="user-header">
                <img src="<?php echo $this->baseUrl(); ?>/assets/calibration/dist/img/profile.png" class="img-circle" alt="User Image">

                <p>
                  ADMINISTRATOR
                  <small>Calibration Recall System</small>
                </p>
              </li>
              <!-- Menu Footer-->
              <li class="user-footer">
                <div class="pull-right">
                    <a href="<?php echo $this->baseUrl(); ?>/logout" class="btn btn-default btn-flat"><i class="fa fa-power-off"></i>&nbsp; Logout</a>
                </div>
              </li>
            </ul>
          </li>
        </ul>
      </div>
    </nav>
  </header>

  <!-- =============================================== -->

  <!-- Left side column. contains the sidebar -->
  <aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
      <!-- Sidebar user panel -->
      <div class="user-panel">
        <div class="pull-left image">
          <img src="<?php echo $this->baseUrl(); ?>/assets/calibration/dist/img/profile.png" class="img-circle" alt="User Image">
        </div>
        <div class="pull-left info">
          <p>Administrator</p>  
        </div>
      </div>
      <!-- sidebar menu: : style can be found in sidebar.less -->
      <ul class="sidebar-menu">
        <li class="header">MAIN NAVIGATION</li>
        <li>
          <a href="<?php echo $this->baseUrl(); ?>/calibration">
            <i class="fa fa-dashboard"></i> <span>Dashboard</span>
          </a>
        </li>
        
        <!-- FILE-->
        <li class="treeview">
          <a href="#">
            <i class="fa fa-file-text-o"></i> <span>File</span> <i class="fa fa-angle-left pull-right"></i>
          </a>
          <ul class="treeview-menu">
            <li><a href="<?php echo $this->baseUrl(); ?>/file/reminder"><i class="fa fa-circle-o"></i> Reminder</a></li>
            <li><a href="<?php echo $this->baseUrl(); ?>/file/personnel-data"><i class="fa fa-circle-o"></i> Personnel Data</a></li>
          </ul>
        </li>
        
        <!-- RECORD-->
        <li class="treeview">
          <a href="#">
            <i class="fa fa-th"></i> <span>Record</span> <i class="fa fa-angle-left pull-right"></i>
          </a>
          <ul class="treeview-menu">
            <li><a href="<?php echo $this->baseUrl(); ?>/record/add-record"><i class="fa fa-circle-o"></i> Add Record</a></li>
            <li><a href="<?php echo $this->baseUrl(); ?>/record/search-record"><i class="fa fa-circle-o"></i> Search Record</a></li>
            <li><a href="<?php echo $this->baseUrl(); ?>/record/calibration"><i class="fa fa-circle-o"></i> Calibration</a></li>
            <li><a href="<?php echo $this->baseUrl(); ?>/record/gr-study"><i class="fa fa-circle-o"></i> GR&R Study</a></li>
            <li><a href="javascript:;" id="incoming_log"><i class="fa fa-circle-o"></i> Incoming Log</a></li>
            <li><a href="<?php echo $this->baseUrl(); ?>/record/active-pr"><i class="fa fa-circle-o"></i> Active PR</a></li>
            <li><a href="javascript:;"id="equip_notice"><i class="fa fa-circle-o"></i> Equipment Notice</a></li>
          </ul>
        </li>
        
        <!-- PRINT-->
        <li class="treeview">
          <a href="#">
            <i class="fa fa-print"></i> <span>Print</span> <i class="fa fa-angle-left pull-right"></i>
          </a>
          <ul class="treeview-menu">
            <li><a href="<?php echo $this->baseUrl(); ?>/print/recall-system"><i class="fa fa-circle-o"></i> Recall System</a></li>
            <li><a href="<?php echo $this->baseUrl(); ?>/print/recall-summary"><i class="fa fa-circle-o"></i> Recall Summary</a></li>
            <li><a href="<?php echo $this->baseUrl(); ?>/print/gr-summary"><i class="fa fa-circle-o"></i> GR&R Summary</a></li>
            <li><a href="<?php echo $this->baseUrl(); ?>/print/recall-forecast"><i class="fa fa-circle-o"></i> Recall Forecast</a></li>
          </ul>
        </li>
        
        <!-- OTHERS-->
        <li class="treeview">
          <a href="#">
            <i class="fa fa-tasks"></i> <span>Others</span> <i class="fa fa-angle-left pull-right"></i>
          </a>
          <ul class="treeview-menu">
            <li><a href="<?php echo $this->baseUrl(); ?>/upload"><i class="fa fa-circle-o"></i> Upload Database</a></li>
            <li><a href="javascript:;" id="notSetup"><i class="fa fa-circle-o"></i> Add User</a></li>
            <li><a href="javascript:;" id="notSetup1"><i class="fa fa-circle-o"></i> Administrator Settings</a></li>  
          </ul>
        </li>
        <li class="header"></li>
        <li><a href="<?php echo $this->baseUrl(); ?>/logout"><i class="fa fa-power-off"></i> <span>Logout</span></a></li>
      </ul>
    </section>
    <!-- /.sidebar -->
  </aside>

  <!-- =============================================== -->

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">

    <!-- Main content -->
    <section class="content">
        <!--Zend Content-->
        <?php echo $this->layout()->content; ?>
        <!---Zend content end-->
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->

  <footer class="main-footer">
    <div class="pull-right hidden-xs">
       <b>Version</b> 0.0.1
    </div>
    <strong>Copyright &copy; 2016-2017 <a href="http://www.teamglac.com/">Team Pacific Corporation</a>.</strong> All rights
    reserved.
  </footer>

<!-- Modal -->
<div class="modal fade bs-example" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Modal title</h4>
      </div>
      <div class="modal-body">
        Sample content ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>

<!-- jQuery 2.2.0 -->
<script src="<?php echo $this->baseUrl(); ?>/assets/calibration/plugins/jQuery/jQuery-2.2.0.min.js"></script>
<!-- Bootstrap 3.3.5 -->
<script src="<?php echo $this->baseUrl(); ?>/assets/calibration/bootstrap/js/bootstrap.min.js"></script>
<!-- DataTables -->
<script src="<?php echo $this->baseUrl(); ?>/assets/calibration/plugins/datatables/jquery.dataTables.min.js"></script>
<script src="<?php echo $this->baseUrl(); ?>/assets/calibration/plugins/datatables/dataTables.bootstrap.min.js"></script>
<!-- SlimScroll -->
<script src="<?php echo $this->baseUrl(); ?>/assets/calibration/plugins/slimScroll/jquery.slimscroll.min.js"></script>
<!-- FastClick -->
<script src="<?php echo $this->baseUrl(); ?>/assets/calibration/plugins/fastclick/fastclick.js"></script>
<!-- AdminLTE App -->
<script src="<?php echo $this->baseUrl(); ?>/assets/calibration/dist/js/app.min.js"></script>
<!-- AdminLTE for demo purposes -->
<script src="<?php echo $this->baseUrl(); ?>/assets/calibration/dist/js/demo.js"></script>
<!-- date-range-picker -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.6/moment.min.js"></script>
<script src="<?php echo $this->baseUrl(); ?>/assets/calibration/plugins/daterangepicker/daterangepicker.js"></script>

<!-- page script -->
<script>
  $(function () {
    $("#recordTable").DataTable();
    $("#fileTable").DataTable();
//    $('#fileTable').DataTable({
//      "paging": true,
//      "lengthChange": false,
//      "searching": false,
//      "ordering": true,
//      "info": true,
//      "autoWidth": false
//    });
    
    //not yet setup
    $("#notSetup").on("click",function(ev){
        ev.preventDefault();
        alert("Not yet setup.");
    });
    $("#notSetup1").on("click",function(ev){
        ev.preventDefault();
        alert("Not yet setup.");
    });
    $("#incoming_log").on("click",function(ev){
        ev.preventDefault();
        alert("Incoming log.");
    });
    $("#equip_notice").on("click",function(ev){
        ev.preventDefault();
        alert("Equipment notice.");
    });
    
    //single date picker
    $('[name="date_calibration"]').daterangepicker({
        singleDatePicker: true,
        showDropdowns: true
    });
    $('[name="next_calibration"]').daterangepicker({
        singleDatePicker: true,
        showDropdowns: true
    });
    $('[name="dateRemind"]').daterangepicker({
        singleDatePicker: true,
        showDropdowns: true
    });
    $('[name="date_performed"]').daterangepicker({
        singleDatePicker: true,
        showDropdowns: true
    });
    
    //Date range picker
    $('#reservation').daterangepicker();
    //Date range picker with time picker
    $('#reservationtime').daterangepicker({timePicker: true, timePickerIncrement: 30, format: 'MM/DD/YYYY h:mm A'});
    //Date range as a button
    $('#daterange-btn').daterangepicker(
        {
          ranges: {
            'Today': [moment(), moment()],
            'Yesterday': [moment().subtract(1, 'days'), moment().subtract(1, 'days')],
            'Last 7 Days': [moment().subtract(6, 'days'), moment()],
            'Last 30 Days': [moment().subtract(29, 'days'), moment()],
            'This Month': [moment().startOf('month'), moment().endOf('month')],
            'Last Month': [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')]
          },
          startDate: moment().subtract(29, 'days'),
          endDate: moment()
        },
        function (start, end) {
          $('#reportrange span').html(start.format('MMMM D, YYYY') + ' - ' + end.format('MMMM D, YYYY'));
        }
    );
  });
</script>

</body>
</html>