<!DOCTYPE html>
<html lang="en">
<head>
	
	<!-- start: Meta -->
	<meta charset="utf-8">
	<title> Calibration Recall System </title>
	<meta name="description" content="">
	<meta name="author" content="Rexie Galban">
	<meta name="keyword" content="MIS-Project">
	<!-- end: Meta -->
	
	<!-- start: Mobile Specific -->
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!-- end: Mobile Specific -->
	
	<!-- start: CSS -->
	<link id="bootstrap-style" href="<?php echo $this->baseUrl(); ?>/assets/bootstrap/css/bootstrap.min.css" rel="stylesheet">
	<link href="<?php echo $this->baseUrl(); ?>/assets/bootstrap/css/bootstrap-responsive.min.css" rel="stylesheet">
	<link id="base-style" href="<?php echo $this->baseUrl(); ?>/assets/bootstrap/css/style.css" rel="stylesheet">
	<link id="base-style-responsive" href="<?php echo $this->baseUrl(); ?>/assets/bootstrap/css/style-responsive.css" rel="stylesheet">
	<link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800&subset=latin,cyrillic-ext,latin-ext' rel='stylesheet' type='text/css'>
	<!-- end: CSS -->
	

	<!-- The HTML5 shim, for IE6-8 support of HTML5 elements -->
	<!--[if lt IE 9]>
	  	<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
		<link id="ie-style" href="css/ie.css" rel="stylesheet">
	<![endif]-->
	
	<!--[if IE 9]>
		<link id="ie9style" href="css/ie9.css" rel="stylesheet">
	<![endif]-->
		
	<!-- start: Favicon -->
	<link rel="shortcut icon" href="<?php echo $this->baseUrl(); ?>/assets/bootstrap/img/calibration.jpg">
	<!-- end: Favicon -->
	
			<style type="text/css">
			body { background: url(<?php echo $this->baseUrl(); ?>/assets/bootstrap/img/bg-login.jpg) !important; }
		</style>
		
		
		
</head>

<body>
		<div class="container-fluid-full">
		<div class="row-fluid">
					
			<div class="row-fluid">
				<div class="login-box">
					<div class="icons">
						<a href="jascript:;"><i class="halflings-icon home"></i></a>
						<a href="jascript:;"><i class="halflings-icon cog"></i></a>
					</div>
					<h2>Administrator Login</h2>
                                        <div class="clearfix"></div>
                                        <noscript>
                                            <div class="box-content alerts">
                                                    <div class="alert alert-error">
                                                            <button type="button" class="close" data-dismiss="alert">×</button>
                                                            <strong>Error!</strong> Invalid user account.
                                                    </div>
                                            </div>                                        
                                        </noscript>
					<form class="form-horizontal" action="<?php echo $this->baseUrl(); ?>/login" method="post">
						<fieldset>
							
							<div class="input-prepend" title="Username">
								<span class="add-on"><i class="halflings-icon user"></i></span>
								<input class="input-large span10" name="username" id="username" type="text" placeholder="type username" required/>
							</div>
							<div class="clearfix"></div>

							<div class="input-prepend" title="Password">
								<span class="add-on"><i class="halflings-icon lock"></i></span>
								<input class="input-large span10" name="password" id="password" type="password" placeholder="type password" required/>
							</div>
							<div class="clearfix"></div>
							
							<label class="remember" for="remember"><input type="checkbox" id="remember" />Remember me</label>

							<div class="button-login">	
								<button type="submit" class="btn btn-primary">Login</button>
							</div>
							<div class="clearfix"></div>
                                                </fieldset>
					</form>
					<hr />
					<h3>Forgot Password?</h3>
					<p>
						No problem, <a href="#" onclick="getPassword()">click here</a> to get a new password.
					</p>	
				</div><!--/span-->
<!--                                <h1><center> <b>Calibration Recall System</b> </center></h1>-->
			</div><!--/row-->
			

	</div><!--/.fluid-container-->
	
		</div><!--/fluid-row-->
	
	<!-- start: JavaScript-->
        <script>
            function getPassword(){
                alert("MIS.");
            }
        </script>

		<script src="<?php echo $this->baseUrl(); ?>/assets/bootstrap/js/jquery-1.9.1.min.js"></script>
	<script src="<?php echo $this->baseUrl(); ?>/assets/bootstrap/js/jquery-migrate-1.0.0.min.js"></script>
	
		<script src="<?php echo $this->baseUrl(); ?>/assets/bootstrap/js/jquery-ui-1.10.0.custom.min.js"></script>
	
		<script src="<?php echo $this->baseUrl(); ?>/assets/bootstrap/js/jquery.ui.touch-punch.js"></script>
	
		<script src="<?php echo $this->baseUrl(); ?>/assets/bootstrap/js/modernizr.js"></script>
	
		<script src="<?php echo $this->baseUrl(); ?>/assets/bootstrap/js/bootstrap.min.js"></script>
	
		<script src="<?php echo $this->baseUrl(); ?>/assets/bootstrap/js/jquery.cookie.js"></script>
	
		<script src='<?php echo $this->baseUrl(); ?>/assets/bootstrap/js/fullcalendar.min.js'></script>
	
		<script src='<?php echo $this->baseUrl(); ?>/assets/bootstrap/js/jquery.dataTables.min.js'></script>

		<script src="<?php echo $this->baseUrl(); ?>/assets/bootstrap/js/excanvas.js"></script>
	<script src="<?php echo $this->baseUrl(); ?>/assets/bootstrap/js/jquery.flot.js"></script>
	<script src="<?php echo $this->baseUrl(); ?>/assets/bootstrap/js/jquery.flot.pie.js"></script>
	<script src="<?php echo $this->baseUrl(); ?>/assets/bootstrap/js/jquery.flot.stack.js"></script>
	<script src="<?php echo $this->baseUrl(); ?>/assets/bootstrap/js/jquery.flot.resize.min.js"></script>
	
		<script src="<?php echo $this->baseUrl(); ?>/assets/bootstrap/js/jquery.chosen.min.js"></script>
	
		<script src="<?php echo $this->baseUrl(); ?>/assets/bootstrap/js/jquery.uniform.min.js"></script>
		
		<script src="<?php echo $this->baseUrl(); ?>/assets/bootstrap/js/jquery.cleditor.min.js"></script>
	
		<script src="<?php echo $this->baseUrl(); ?>/assets/bootstrap/js/jquery.noty.js"></script>
	
		<script src="<?php echo $this->baseUrl(); ?>/assets/bootstrap/js/jquery.elfinder.min.js"></script>
	
		<script src="<?php echo $this->baseUrl(); ?>/assets/bootstrap/js/jquery.raty.min.js"></script>
	
		<script src="<?php echo $this->baseUrl(); ?>/assets/bootstrap/js/jquery.iphone.toggle.js"></script>
	
		<script src="<?php echo $this->baseUrl(); ?>/assets/bootstrap/js/jquery.uploadify-3.1.min.js"></script>
	
		<script src="<?php echo $this->baseUrl(); ?>/assets/bootstrap/js/jquery.gritter.min.js"></script>
	
		<script src="<?php echo $this->baseUrl(); ?>/assets/bootstrap/js/jquery.imagesloaded.js"></script>
	
		<script src="<?php echo $this->baseUrl(); ?>/assets/bootstrap/js/jquery.masonry.min.js"></script>
	
		<script src="<?php echo $this->baseUrl(); ?>/assets/bootstrap/js/jquery.knob.modified.js"></script>
	
		<script src="<?php echo $this->baseUrl(); ?>/assets/bootstrap/js/jquery.sparkline.min.js"></script>
	
		<script src="<?php echo $this->baseUrl(); ?>/assets/bootstrap/js/counter.js"></script>
	
		<script src="<?php echo $this->baseUrl(); ?>/assets/bootstrap/js/retina.js"></script>

		<script src="<?php echo $this->baseUrl(); ?>/assets/bootstrap/js/custom.js"></script>
	<!-- end: JavaScript-->
	
</body>
</html>
