<script src="<?php echo $this->baseUrl(); ?>/assets/calibration/plugins/jQuery/jQuery-2.2.0.min.js"></script>
<script src="<?php echo $this->baseUrl(); ?>/assets/js/calibration/calibration.js"></script>

<div class="row">
    <div class="col-md-12">
      <!-- general form elements -->
      <div class="box box-primary">
        <div class="box-header with-border">
          <h3 class="box-title">File Reminder</h3>
        </div>
        <!-- /.box-header -->
        <div class="box-body">
            
          <a href="javascript:;" id="addReminder" class="pull-right btn btn-primary"><i class="fa fa-fw fa-plus"></i> Add Reminder</a>
          <br /><br /><br />
          <table id="recordTable" class="table table-bordered table-hover">
            <thead>
            <tr>
              <th>ID</th>
              <th>Date to Remind</th>
              <th>Message</th>
              <th>Status</th>
              <th>Action</th>
            </tr>
            </thead>
            <tbody>

            <?php foreach ($this->reminderContent as $list) { ?>
                <tr>
                    <td><?php echo $list['id']; ?></td>
                    <td><?php echo date("M d, Y",  strtotime($list['dateRemind'])); ?></td>
                    <td><?php echo $list['message']; ?></td>
                    <td><?php echo $list['status']; ?></td>
                    <td class='center'>
                            <a onclick="viewReminderContent(<?php echo $list['id'] ?>)" href="javascript:;"> View </a> |
                            <a onclick="editReminderContent(<?php echo $list['id'] ?>)" href="javascript:;"> Edit </a> |
                            <a onclick="deleteReminderEntry(<?php echo $list['id'] ?>)" href="javascript:;"> Delete </a>
                    </td>

                </tr>

            <?php } ?>

            </tbody>
            <tfoot>
            <tr>
              <th>ID</th>
              <th>Date to Remind</th>
              <th>Message</th>
              <th>Status</th>
              <th>Action</th>
            </tr>
            </tfoot>
          </table>
        </div>
      </div>
      <!-- /.box -->

    </div>
</div>


<!-- Modal -->
<div class="modal  bs-example-modal" id="reminderModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">File Reminder</h4>
      </div>
        <form class="form-horizontal" method="POST" action="/file/add-reminder">
        <div class="modal-body">
              <div id="addReminderForm" style="">
                  <label class="control-label" for="dateRemind">Reminder Date :</label>
                    <div class="input-group col-md-10">
                        <input type="text" class="form-control" name="dateRemind" placeholder="Reminder Date" required />
                        <div class="input-group-addon">
                            <span class="glyphicon glyphicon-calendar"></span>
                        </div>
                    </div>
                    <div class="input-group col-md-10">
                        <label class="control-label" for="message">Message :</label>
                        <div class="controls">
                            <textarea class="form-control" name="message" rows="3" placeholder="Type your message..." required></textarea>
                        </div>
                    </div>
              </div>
              <div id="reminder-content"></div>
        </div>
        <div class="modal-footer">
            <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
            <button class="btn btn-primary" id="addReminder-btn" style="display:none;">Add</button>
            <button type="button" class="btn btn-primary" id="updateReminder-btn" style="display:none;">Update</button>
        </div>
        </form>
    </div>
  </div>
</div>

<script>
$("#addReminder").on("click",function(){
    $("#reminder-content").html('');
});
</script>