<script src="<?php echo $this->baseUrl(); ?>/assets/calibration/plugins/jQuery/jQuery-2.2.0.min.js"></script>
<script src="<?php echo $this->baseUrl(); ?>/assets/js/calibration/calibration.js"></script>


<?php  echo "<h3 class=''>Today is ".$this->today."</h3>";  ?>
<hr />

<!--################# SCHEDULES #################-->
<div class="row">
<!-- /.col -->
<div class="col-md-12">
  <div class="box box-success">
    <div class="box-header with-border">
      <h3 class="box-title">Schedules</h3>

      <div class="box-tools pull-right">
        <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
        </button>
      </div>
      <!-- /.box-tools -->
    </div>
    <!-- /.box-header -->
    <div class="box-body">
        
        <!--today-->
        <div class="col-lg-3 col-xs-6">
          <!-- small box -->
          <div class="small-box bg-green">
            <div class="inner">
              <h3><?php echo $this->todayCntr;?></h3>

              <p>Schedule for TODAY</p>
            </div>
            <div class="icon">
              <i class="fa fa-calendar"></i>
            </div>
            <a href="<?php echo $this->baseUrl(); ?>/calibration/schedule-today" class="small-box-footer">View <i class="fa fa-arrow-circle-right"></i></a>
          </div>
        </div>

        <!--tomorrow-->
        <div class="col-lg-3 col-xs-6">
          <!-- small box -->
          <div class="small-box bg-blue">
            <div class="inner">
              <h3><?php echo $this->tomorrowCntr;?></h3>

              <p>On <?php echo $this->tomorrow; ?></p>
            </div>
            <div class="icon">
              <i class="fa fa-calendar"></i>
            </div>
            <a href="<?php echo $this->baseUrl(); ?>/calibration/schedule-tomorrow" class="small-box-footer">View <i class="fa fa-arrow-circle-right"></i></a>
          </div>
        </div>

        <!--next other day-->
        <div class="col-lg-3 col-xs-6">
          <!-- small box -->
          <div class="small-box bg-aqua">
            <div class="inner">
              <h3><?php echo $this->nextdayCntr;?></h3>

              <p>On <?php echo $this->nextday; ?></p>
            </div>
            <div class="icon">
              <i class="fa fa-calendar"></i>
            </div>
            <a href="<?php echo $this->baseUrl(); ?>/calibration/schedule-nextday" class="small-box-footer">View <i class="fa fa-arrow-circle-right"></i></a>
          </div>
        </div>

        <!--backlag-->
        <div class="col-lg-3 col-xs-6">
          <!-- small box -->
          <div class="small-box bg-red">
            <div class="inner">
              <h3><?php echo $this->backlagCntr;?></h3>

              <p>Backlag Schedule</p>
            </div>
            <div class="icon">
              <i class="fa fa-calendar"></i>
            </div>
            <a href="<?php echo $this->baseUrl(); ?>/calibration/schedule-backlag" class="small-box-footer">View <i class="fa fa-arrow-circle-right"></i></a>
          </div>
        </div>
    </div>
    <!-- /.box-body -->
  </div>
  <!-- /.box -->
</div>
<!-- /.col -->
</div>
<!-- /.row -->

<!--################# REMINDERS #################-->
<div class="row">
<!-- /.col -->
<div class="col-md-12">
  <div class="box box-warning">
    <div class="box-header with-border">
      <h3 class="box-title">Reminders</h3>

      <div class="box-tools pull-right">
        <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
        </button>
      </div>
      <!-- /.box-tools -->
    </div>
    <!-- /.box-header -->
    <div class="box-body" style="">
        <?php if($this->reminderContent){
            
            foreach($this->reminderContent as $list){ ?>
                <div class="callout callout-warning1">
                    <h4><?php echo date("l - F d, Y",strtotime($list['dateRemind'])); ?></h4>
                    <?php echo $list['message']; ?>
                    &nbsp;
                    <a style="color:#3C8DBC;" href="javascript:;" onclick="viewReminderContent(<?php echo $list['id']; ?>)" class="small-box-footer">
                        View 
                        <i class="fa fa-arrow-circle-right"></i>
                    </a>
                </div>
            <?php }
        }else{
            echo "No reminders!";
        }  ?>
    </div>
    <!-- /.box-body -->
  </div>
  <!-- /.box -->
</div>
<!-- /.col -->
</div>
<!-- /.row -->

<!-- Modal -->
<div class="modal  bs-example-modal" id="reminderModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">File Reminder</h4>
      </div>
      <div class="modal-body">
          <div id="reminder-content"></div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
<!--        <button type="button" class="btn btn-primary" id="update-btn" style="display:none;">Update</button>-->
<!--        <button type="button" class="btn btn-primary">Calibrate</button>-->
      </div>
    </div>
  </div>
</div>