<script type="text/javascript" src="<?php echo $this->baseUrl() ?>/assets/js/user/add.js"></script>

<form id="ajaxForm" method="POST">
    Uname : <input type="text" id="uname" name="uname" required="true" /></br>
    Password : <input type="password" id="password" name="password" required="true" /></br>
    Confirm Pass: <input type="password" id="conf_pass" name="conf_pass" required="true" /></br>
    <button>Save</button>
</form>


    



<form id="ajaxSearch" method="POST">
    <div id="table">
        
        <table width="100%" id="all-users-table">
            <thead>
                <tr>
                    <th>Username</th>
                    <th>Password</th>
                    <th>Fullname</th>
                </tr>
            </thead>
            <tbody>
                
            </tbody>
        </table>
        
        
    </div>
    <button id="show">Show All</button>
</form>


    



<form id="ajaxHtml">
    <div id="html-box">
        <!--Ajax View Here-->
    </div>
    <button>Get View</button>
</form>