<form id="ajaxSearch" method="POST">
    <div id="table">
        
        <table width="100%" id="all-users-table">
            <thead>
                <tr>
                    <th>Username</th>
                    <th>Password</th>
                    <th>Fullname</th>
                </tr>
            </thead>
            <tbody>
                
            </tbody>
        </table>
        
        
    </div>
    <button id="show">Show All</button>
</form>