<?php date_default_timezone_set("Asia/Manila"); ?>

<div id="dashboard">

    <div class="pull-right">
        <a href="#addUser" role="button" class="btn btn-primary" data-toggle="modal">
            <i class="icon-plus icon-white"></i>
            Add User
        </a>
    </div>

    <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" id="example">
        <caption><h4>List of Users</h4></caption>
        <thead>
            <tr>
                <th>User ID</th>
                <th>Username</th>
                <th>Full name</th>
                <th>Type</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
	        <?php foreach ($this->userList as $list) { ?>
	            <tr class="odd gradeX">
	                <td><?php echo $list['id']; ?></td>
	                <td><?php echo $list['uname']; ?></td>
	                <td><?php echo $list['fullname']; ?></td>
	                <td><?php echo $list['type']; ?></td>
	                <td class='center'>
	                	<a href="<?php echo $this->baseUrl() ?>/user/view/id/<?php echo $list['id']; ?>">
	                		View 
	                	</a> | 
	                	<a href="<?php echo $this->baseUrl() ?>/user/edit/id/<?php echo $list['id']; ?> ">
	                		Edit 
	                	</a> | 
	                	<a href="<?php echo $this->baseUrl() ?>/user/delete/id/<?php echo $list['id']; ?> ">
	                		Delete 
	                	</a>
	                </td>
	                <input type="hidden" name="id" value="<?php echo $list['id']; ?>">
	                
	            </tr>
	        		
	        <?php } ?>
        </tbody>
    </table>
    <div class="clearfix"></div>
</div>

<!-- Add User Modal -->
<div class="modal hide fade addUserModal" style="display:none" id="addUser" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div>
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            <h3 id="myModalLabel">Add User</h3>
        </div>
        <div class="modal-body">
            <form id="ajaxForm" class="form-horizontal" method="POST">
                <div class="control-group">
                    <label class="control-label" for="descrp">Username :</label>
                    <div class="controls">
                        <input type="text" name="username" placeholder="Username" required />
                    </div>
                </div>

    		<div class="control-group">
                    <label class="control-label" for="password">Password :</label>
                    <div class="controls">
                        <input type="password" name="password" placeholder="Password" required/>
                    </div>
                </div>

    		<div class="control-group">
                    <label class="control-label" for="fullname">Full name :</label>
                    <div class="controls">
                        <input type="text" name="fullname" placeholder="Full name" required/>
                    </div>
                </div>

                <div class="control-group">
                    <label class="control-label" for="type">Type :</label>
                    <div class="controls">
                    <select name="type" required>
                    	<option value="">Please Select</option>
                        <option value="Administrator">Administrator</option>
                        <option value="Supervisor">Supervisor</option>
                        <option value="Encoder">Encoder</option>
                    </select>
                    </div>
                </div>
		        <div class="modal-footer">
		            <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
		            <button id="addClick" class="btn btn-primary">Add</button>
		        </div>
            </form>
    </div>
</div>
    <script type="text/javascript" src="<?php echo $this->baseUrl() ?>/assets/js/user/add.js"></script>
<script type="text/javascript">
    $(document).ready(function() {
        $('#example').DataTable( {
            "pagingType": "full_numbers"
        } );
    } );
</script>